# Generated by Django 4.1.4 on 2023-05-18 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='ContactData',
        ),
    ]
